Issue #682 - Bug: Actions workflow pushes docker images to GitHub container registry, Stop pushing semantic version to dockerhub
Signed-off-by: blakep7 <pearsonblake9@gmail.com>

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -12,6 +12,7 @@ on:
 # Variables available to all jobs
 env:
   IMAGE_REPO: ${{ vars.DOCKERHUB_REPO }}
+  GITHUB_CONTAINER_REGISTRY: ghcr.io/${{ github.repository_owner }}
   BUILD_NUMBER: ${{ github.run_number }}
 
 # Jobs that will run when the workflow is triggered
@@ -26,6 +27,25 @@ jobs:
       IMAGE_VERSION: ''
     
     steps:
+      # Ensure that the repo variables and secrets are set before running any other steps
+      - name: Check User Set Variables
+        run: |
+          if [[ -z "$DOCKER_USER" ]]; then \
+          echo "::error::Secret DOCKER_USER was not set"; \
+          exit 1; \
+          fi
+          if [[ -z "$DOCKER_TOKEN" ]]; then \
+          echo "::error::Secret DOCKER_TOKEN was not set"; \
+          exit 1; \
+          fi
+          if [[ -z "$IMAGE_REPO" ]]; then \
+          echo "::error::Variable DOCKERHUB_REPO was not set"; \
+          exit 1; \
+          fi
+        env:
+          DOCKER_USER: ${{ secrets.DOCKER_USER }}
+          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
+
       # Upgrade Docker engine version, needed for building images.
       - name: Install Latest Docker Version
         run: |
@@ -40,6 +60,14 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_TOKEN }}
+        
+      # Authenticate GHCR to allow pushing to our alternate image registry
+      - name: Login to Github Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
       # Checkout our Github repo
       - name: Checkout Github Repo
@@ -75,10 +103,10 @@ jobs:
       # Push Docker images to Dockerhub
       - name: Publish Image to Dockerhub
         run: |
-          docker tag openhorizon/amd64_exchange-api:${IMAGE_VERSION} ${IMAGE_REPO}/amd64_exchange-api:${IMAGE_VERSION}-${BUILD_NUMBER}
           docker tag openhorizon/amd64_exchange-api:${IMAGE_VERSION} ${IMAGE_REPO}/amd64_exchange-api:testing
-          docker push ${IMAGE_REPO}/amd64_exchange-api:${IMAGE_VERSION}-${BUILD_NUMBER}
           if [[ "$GITHUB_REF" == 'refs/heads/master' ]]; then \
           docker push ${IMAGE_REPO}/amd64_exchange-api:testing; \
+          docker tag ${IMAGE_REPO}/amd64_exchange-api:testing ${GITHUB_CONTAINER_REGISTRY}/amd64_exchange-api:testing; \
+          docker push ${GITHUB_CONTAINER_REGISTRY}/amd64_exchange-api:testing; \
           fi
       
